services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/prisma
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "file:/opt/render/project/prisma/prod.db"
      - key: PORT
        value: "3000"

databases:
  - name: chat_db
    plan: free
